name: twig
on:
  push:
    paths:
      - twig.dockerfile
      - twig/**
jobs:
  twig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build twig Image
        run: |
              docker build . -t ghcr.io/erwijet/aspen/twig:latest -f twig.dockerfile
              docker push ghcr.io/erwijet/aspen/twig:latest